"""Pure H3 multimodal contract, prompt compiler, and AutoDL request builder.

This module deliberately performs no provider I/O.  Adapters freeze visual and
audio bytes before entering this boundary; the request builder only encodes
those bytes.  Reference audio is conditioning material, never a target track,
and the audio generated by H3 is the authoritative output.
"""

from __future__ import annotations

import base64
import hashlib
import json
import re
from dataclasses import dataclass, field
from fractions import Fraction
from pathlib import Path
from typing import Literal, Mapping, Sequence

from app.h3 import canonical_json_sha256 as _canonical_sha256


COMPILER_VERSION = "duet.h3-multimodal-context-ir.v1"
MULTIMODAL_WORKFLOW = "minimax_h3_image_audio_to_video_v2_15s"
MULTIMODAL_HD_WORKFLOW = "minimax_h3_image_audio_to_video_v2"

REFERENCE_AUDIO_SEMANTICS = "conditioning_only"
OUTPUT_AUDIO_AUTHORITY = "h3_generated"
MAX_PROMPT_BYTES = 32 * 1024

_IMAGE_MIME_BY_SUFFIX = {
    ".png": "image/png",
    ".jpg": "image/jpeg",
    ".jpeg": "image/jpeg",
    ".webp": "image/webp",
}
_AUDIO_MIME_BY_FORMAT = {"mp3": "audio/mpeg", "wav": "audio/wav"}
_AUDIO_KINDS = frozenset({"voice", "sound_effect", "ambience"})
_SUBJECT_ID = re.compile(r"^S([1-9][0-9]*)$")
_LANGUAGE = re.compile(r"^[A-Za-z][A-Za-z0-9_-]{0,31}$")
_RESERVED_PROMPT_SYNTAX = re.compile(
    r"<(?:/?d\b|Picture\s+\d+|Audio\s+\d+|Subject\s+\d+)>|\(S\d+\)",
    re.IGNORECASE,
)

H3Mode = Literal["multimodal", "multimodal_hd"]
AudioKind = Literal["voice", "sound_effect", "ambience"]


class H3MultimodalContractError(RuntimeError):
    """A stable, local validation failure raised before any provider POST."""

    def __init__(self, code: str) -> None:
        super().__init__(code)
        self.code = code


def _fail(code: str) -> None:
    raise H3MultimodalContractError(code)


def _sha256(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def _is_sha256(value: object) -> bool:
    return (
        isinstance(value, str)
        and len(value) == 64
        and all(character in "0123456789abcdef" for character in value)
    )


def _require_optional_sha256(value: object, code: str) -> None:
    if value is not None and not _is_sha256(value):
        _fail(code)


def _require_positive_integer(value: object, code: str) -> int:
    if isinstance(value, bool) or not isinstance(value, int) or value <= 0:
        _fail(code)
    return value


def _require_nonblank(value: object, code: str, *, maximum: int = 256) -> str:
    if not isinstance(value, str) or not value.strip() or len(value) > maximum:
        _fail(code)
    if any(ord(character) < 32 and character not in "\n\t" for character in value):
        _fail(code)
    return value


def _require_tuple(value: object, code: str) -> tuple:
    if not isinstance(value, tuple):
        _fail(code)
    return value


def _skill_object(
    value: object,
    keys: frozenset[str],
    *,
    code: str = "skill_plan_shape_invalid",
) -> Mapping[str, object]:
    if not isinstance(value, Mapping) or set(value) != keys:
        _fail(code)
    return value


def _skill_list(value: object) -> list[object]:
    if not isinstance(value, list):
        _fail("skill_plan_shape_invalid")
    return value


def _skill_items(value: object, keys: frozenset[str], build) -> tuple:
    return tuple(
        build(_skill_object(item, keys)) for item in _skill_list(value)
    )


@dataclass(frozen=True, slots=True)
class FrozenKeyframe:
    """One already-read image snapshot.  ``order`` is externally 1-based."""

    name: str
    order: int
    data: bytes = field(repr=False)
    sha256: str
    width: int
    height: int
    role: Literal["reference_image"] = "reference_image"

    def __post_init__(self) -> None:
        _require_positive_integer(self.order, "keyframe_order_invalid")
        _require_nonblank(self.name, "keyframe_name_invalid")
        if self.name != Path(self.name).name or "\\" in self.name:
            _fail("keyframe_name_invalid")
        if any(character in self.name for character in "\r\n\t<>"):
            _fail("keyframe_name_invalid")
        if Path(self.name).suffix.lower() not in _IMAGE_MIME_BY_SUFFIX:
            _fail("keyframe_format_invalid")
        if not isinstance(self.data, bytes) or not self.data:
            _fail("keyframe_bytes_invalid")
        if not _is_sha256(self.sha256) or _sha256(self.data) != self.sha256:
            _fail("keyframe_hash_mismatch")
        _require_positive_integer(self.width, "keyframe_dimensions_invalid")
        _require_positive_integer(self.height, "keyframe_dimensions_invalid")
        if self.role != "reference_image":
            _fail("keyframe_role_invalid")


def _keyframe_manifest(frame: FrozenKeyframe) -> dict[str, object]:
    return {
        "name": frame.name,
        "order": frame.order,
        "role": frame.role,
        "sha256": frame.sha256,
        "size_bytes": len(frame.data),
        "width": frame.width,
        "height": frame.height,
    }


@dataclass(frozen=True, slots=True)
class FrozenVisualInput:
    """Generic visual input usable by legacy/canary adapters without a Skill."""

    prompt: str
    prompt_sha256: str
    keyframes: tuple[FrozenKeyframe, ...]
    legacy_plan_sha256: str | None = None
    legacy_meta_sha256: str | None = None
    skill_receipt_sha256: str | None = None

    def __post_init__(self) -> None:
        _require_nonblank(self.prompt, "visual_prompt_invalid", maximum=MAX_PROMPT_BYTES)
        if len(self.prompt.encode("utf-8")) > MAX_PROMPT_BYTES:
            _fail("visual_prompt_invalid")
        if not _is_sha256(self.prompt_sha256) or _sha256(
            self.prompt.encode("utf-8")
        ) != self.prompt_sha256:
            _fail("visual_prompt_hash_mismatch")
        frames = _require_tuple(self.keyframes, "keyframes_not_frozen")
        if not 1 <= len(frames) <= 9:
            _fail("keyframe_count_invalid")
        for expected, frame in enumerate(frames, 1):
            if not isinstance(frame, FrozenKeyframe) or frame.order != expected:
                _fail("keyframe_order_invalid")
            if _sha256(frame.data) != frame.sha256:
                _fail("keyframe_hash_mismatch")
        if len({frame.name for frame in frames}) != len(frames) or len(
            {frame.sha256 for frame in frames}
        ) != len(frames):
            _fail("keyframe_duplicate")
        _require_optional_sha256(self.legacy_plan_sha256, "legacy_plan_hash_invalid")
        _require_optional_sha256(self.legacy_meta_sha256, "legacy_meta_hash_invalid")
        _require_optional_sha256(self.skill_receipt_sha256, "skill_receipt_hash_invalid")


def _visual_manifest(visual: FrozenVisualInput) -> dict[str, object]:
    return {
        "prompt": visual.prompt,
        "prompt_sha256": visual.prompt_sha256,
        "keyframes": [_keyframe_manifest(frame) for frame in visual.keyframes],
        "provenance": {
            "legacy_plan_sha256": visual.legacy_plan_sha256,
            "legacy_meta_sha256": visual.legacy_meta_sha256,
            "skill_receipt_sha256": visual.skill_receipt_sha256,
        },
    }


@dataclass(frozen=True, slots=True)
class FrozenReferenceAudio:
    """One frozen H3 reference-audio artifact, never a target-track promise."""

    order: int
    role: Literal["conditioning_reference"]
    kind: AudioKind
    data: bytes = field(repr=False)
    format: Literal["mp3", "wav"]
    sha256: str
    decoded_sha256: str
    time_base: int
    duration_pts: int

    def __post_init__(self) -> None:
        _require_positive_integer(self.order, "audio_order_invalid")
        if self.role != "conditioning_reference":
            _fail("audio_role_invalid")
        if self.kind not in _AUDIO_KINDS:
            _fail("audio_kind_invalid")
        if self.format not in _AUDIO_MIME_BY_FORMAT:
            _fail("audio_format_invalid")
        if not isinstance(self.data, bytes) or not self.data:
            _fail("audio_bytes_invalid")
        if self.format == "wav" and not (
            len(self.data) >= 12
            and self.data.startswith(b"RIFF")
            and self.data[8:12] == b"WAVE"
        ):
            _fail("audio_format_invalid")
        if self.format == "mp3" and not (
            self.data.startswith(b"ID3")
            or (
                len(self.data) >= 2
                and self.data[0] == 0xFF
                and self.data[1] & 0xE0 == 0xE0
            )
        ):
            _fail("audio_format_invalid")
        if not _is_sha256(self.sha256) or _sha256(self.data) != self.sha256:
            _fail("audio_hash_mismatch")
        if not _is_sha256(self.decoded_sha256):
            _fail("decoded_audio_hash_invalid")
        _require_positive_integer(self.time_base, "audio_time_base_invalid")
        _require_positive_integer(self.duration_pts, "audio_duration_invalid")

def _audio_manifest(audio: FrozenReferenceAudio) -> dict[str, object]:
    return {
        "order": audio.order,
        "role": audio.role,
        "kind": audio.kind,
        "format": audio.format,
        "size_bytes": len(audio.data),
        "sha256": audio.sha256,
        "decoded_sha256": audio.decoded_sha256,
        "probe": {
            "time_base": audio.time_base,
            "duration_pts": audio.duration_pts,
        },
    }


def _require_exact_text(value: object, code: str, *, maximum: int = 2000) -> str:
    text = _require_nonblank(value, code, maximum=maximum)
    if "\n" in text or "\r" in text or "<" in text or ">" in text:
        _fail(code)
    return text


@dataclass(frozen=True, slots=True)
class DialogueLine:
    """One exact spoken line.  It carries order, not a provider PTS promise."""

    order: int
    subject_id: str
    language: str
    text: str

    def __post_init__(self) -> None:
        _require_positive_integer(self.order, "dialogue_order_invalid")
        if not isinstance(self.subject_id, str) or not _SUBJECT_ID.fullmatch(
            self.subject_id
        ):
            _fail("dialogue_subject_invalid")
        if not isinstance(self.language, str) or not _LANGUAGE.fullmatch(self.language):
            _fail("dialogue_language_invalid")
        _require_exact_text(self.text, "dialogue_text_invalid")


@dataclass(frozen=True, slots=True)
class NarrationLine:
    """Ordered off-screen speech, optionally using a frozen voice reference."""

    order: int
    voice_ref: int | None
    language: str
    text: str

    def __post_init__(self) -> None:
        _require_positive_integer(self.order, "narration_order_invalid")
        if self.voice_ref is not None:
            _require_positive_integer(self.voice_ref, "narration_voice_ref_invalid")
        if not isinstance(self.language, str) or not _LANGUAGE.fullmatch(self.language):
            _fail("narration_language_invalid")
        _require_exact_text(self.text, "narration_text_invalid")


@dataclass(frozen=True, slots=True)
class SubjectBinding:
    """Skill-compatible speaker/face/voice binding using 1-based references."""

    subject_id: str
    picture_refs: tuple[int, ...]
    voice_ref: int | None

    def __post_init__(self) -> None:
        match = _SUBJECT_ID.fullmatch(self.subject_id) if isinstance(
            self.subject_id, str
        ) else None
        if match is None:
            _fail("subject_id_invalid")
        pictures = _require_tuple(self.picture_refs, "subject_picture_refs_invalid")
        if not pictures or any(
            isinstance(value, bool) or not isinstance(value, int) or value <= 0
            for value in pictures
        ):
            _fail("subject_picture_refs_invalid")
        if tuple(sorted(set(pictures))) != pictures:
            _fail("subject_picture_refs_invalid")
        if self.voice_ref is not None:
            _require_positive_integer(self.voice_ref, "subject_voice_ref_invalid")


@dataclass(frozen=True, slots=True)
class SoundReference:
    """An exact semantic intent for one ambience or sound-effect reference."""

    audio_index: int
    description: str

    def __post_init__(self) -> None:
        _require_positive_integer(self.audio_index, "sound_reference_invalid")
        _require_exact_text(self.description, "sound_reference_invalid")


@dataclass(frozen=True, slots=True)
class SoundDesign:
    """Strict backend DTO for the Skill's still-evolving sound_design object."""

    narration: tuple[NarrationLine, ...] = ()
    ambience_refs: tuple[SoundReference, ...] = ()
    effects: tuple[SoundReference, ...] = ()

    def __post_init__(self) -> None:
        _require_tuple(self.narration, "sound_design_not_frozen")
        _require_tuple(self.ambience_refs, "sound_design_not_frozen")
        _require_tuple(self.effects, "sound_design_not_frozen")
        if not all(isinstance(item, NarrationLine) for item in self.narration):
            _fail("sound_design_invalid")
        if not all(
            isinstance(item, SoundReference)
            for item in self.ambience_refs + self.effects
        ):
            _fail("sound_design_invalid")


@dataclass(frozen=True, slots=True)
class H3SemanticInput:
    """Strict A-route projection of a frozen target-audio plan."""

    audio_references: tuple[FrozenReferenceAudio, ...]
    dialogue: tuple[DialogueLine, ...]
    subjects: tuple[SubjectBinding, ...]
    sound_design: SoundDesign


@dataclass(frozen=True, slots=True)
class H3Quote:
    credits_per_second: int
    credits: int
    duration: int


@dataclass(frozen=True, slots=True)
class H3MultimodalPlan:
    visual: FrozenVisualInput
    audio_references: tuple[FrozenReferenceAudio, ...]
    dialogue: tuple[DialogueLine, ...]
    subjects: tuple[SubjectBinding, ...]
    sound_design: SoundDesign
    mode: H3Mode
    duration: int
    resolution: str
    aspect_ratio: str
    workflow: str
    quote: H3Quote
    plan_id: str
    revision: int
    effective_prompt: str
    effective_prompt_sha256: str
    compiler_version: str = COMPILER_VERSION
    audio_required: Literal[True] = True
    reference_audio_semantics: Literal["conditioning_only"] = (
        REFERENCE_AUDIO_SEMANTICS
    )
    output_audio_authority: Literal["h3_generated"] = OUTPUT_AUDIO_AUTHORITY
    plan_sha256: str = field(init=False)

    def __post_init__(self) -> None:
        object.__setattr__(self, "plan_sha256", _canonical_sha256(_plan_manifest(self)))


@dataclass(frozen=True, slots=True)
class H3MultimodalRequest:
    plan: H3MultimodalPlan
    approved_plan_sha256: str
    approved_by: str
    idempotency_key: str
    request_sha256: str = field(init=False)

    def __post_init__(self) -> None:
        object.__setattr__(
            self, "request_sha256", _canonical_sha256(_request_manifest(self))
        )


@dataclass(frozen=True, slots=True)
class BuiltAutodlRequest:
    """Pure build result.  A lifecycle/ledger owner may later choose to POST it."""

    workflow: str
    body: dict[str, object]
    idempotency_key: str
    request_sha256: str
    plan_sha256: str
    payload_sha256: str
    output_audio_authority: Literal["h3_generated"] = OUTPUT_AUDIO_AUTHORITY


def _dialogue_manifest(line: DialogueLine) -> dict[str, object]:
    return {
        "order": line.order,
        "subject_id": line.subject_id,
        "language": line.language,
        "text": line.text,
    }


def _narration_manifest(line: NarrationLine) -> dict[str, object]:
    return {
        "order": line.order,
        "voice_ref": line.voice_ref,
        "language": line.language,
        "text": line.text,
    }


def _subject_manifest(subject: SubjectBinding) -> dict[str, object]:
    return {
        "subject_id": subject.subject_id,
        "picture_refs": list(subject.picture_refs),
        "voice_ref": subject.voice_ref,
    }


def _sound_reference_manifest(reference: SoundReference) -> dict[str, object]:
    return {
        "audio_index": reference.audio_index,
        "description": reference.description,
    }


def _sound_design_manifest(sound_design: SoundDesign) -> dict[str, object]:
    return {
        "narration": [
            _narration_manifest(line) for line in sound_design.narration
        ],
        "ambience_refs": [
            _sound_reference_manifest(item) for item in sound_design.ambience_refs
        ],
        "effects": [
            _sound_reference_manifest(item) for item in sound_design.effects
        ],
    }


def _plan_manifest(plan: H3MultimodalPlan) -> dict[str, object]:
    return {
        "compiler": {
            "version": plan.compiler_version,
            "effective_prompt": plan.effective_prompt,
            "effective_prompt_sha256": plan.effective_prompt_sha256,
        },
        "visual": _visual_manifest(plan.visual),
        "audio_references": [
            _audio_manifest(audio) for audio in plan.audio_references
        ],
        "subjects": [_subject_manifest(subject) for subject in plan.subjects],
        "dialogue": [_dialogue_manifest(line) for line in plan.dialogue],
        "sound_design": _sound_design_manifest(plan.sound_design),
        "execution": {
            "mode": plan.mode,
            "duration": plan.duration,
            "resolution": plan.resolution,
            "aspect_ratio": plan.aspect_ratio,
            "workflow": plan.workflow,
            "audio_required": plan.audio_required,
            "reference_audio_semantics": plan.reference_audio_semantics,
            "output_audio_authority": plan.output_audio_authority,
        },
        "quote": {
            "credits_per_second": plan.quote.credits_per_second,
            "credits": plan.quote.credits,
            "duration": plan.quote.duration,
        },
        "plan_id": plan.plan_id,
        "revision": plan.revision,
    }


def _request_manifest(request: H3MultimodalRequest) -> dict[str, object]:
    return {
        "plan_sha256": request.plan.plan_sha256,
        "approved_plan_sha256": request.approved_plan_sha256,
        "approved_by": request.approved_by,
        "idempotency_key": request.idempotency_key,
    }


def _execution_spec(
    *, mode: object, resolution: object, aspect_ratio: object, duration: object
) -> tuple[str, H3Quote]:
    if mode not in {"multimodal", "multimodal_hd"}:
        _fail("mode_invalid")
    if aspect_ratio not in {"16:9", "9:16"}:
        _fail("aspect_ratio_invalid")
    if isinstance(duration, bool) or not isinstance(duration, int):
        _fail("duration_invalid")
    if mode == "multimodal":
        if resolution not in {"480p", "768p"}:
            _fail("resolution_invalid")
        if not 4 <= duration <= 15:
            _fail("duration_invalid")
        workflow = MULTIMODAL_WORKFLOW
        rate = 6 if resolution == "480p" else 8
    else:
        if resolution != "1080p":
            _fail("resolution_invalid")
        if not 4 <= duration <= 10:
            _fail("duration_invalid")
        workflow = MULTIMODAL_HD_WORKFLOW
        rate = 12
    return workflow, H3Quote(rate, rate * duration, duration)


def _validate_visual(visual: object) -> FrozenVisualInput:
    if not isinstance(visual, FrozenVisualInput):
        _fail("visual_input_invalid")
    if _sha256(visual.prompt.encode("utf-8")) != visual.prompt_sha256:
        _fail("visual_prompt_hash_mismatch")
    for expected, frame in enumerate(visual.keyframes, 1):
        if frame.order != expected:
            _fail("keyframe_order_invalid")
        if _sha256(frame.data) != frame.sha256:
            _fail("keyframe_hash_mismatch")
    return visual


def _validate_audio_references(
    audio_references: object,
) -> tuple[FrozenReferenceAudio, ...]:
    audios = _require_tuple(audio_references, "audio_not_frozen")
    if not 1 <= len(audios) <= 3:
        _fail("audio_count_invalid")
    total = Fraction(0, 1)
    for expected, audio in enumerate(audios, 1):
        if not isinstance(audio, FrozenReferenceAudio) or audio.order != expected:
            _fail("audio_order_invalid")
        if _sha256(audio.data) != audio.sha256:
            _fail("audio_hash_mismatch")
        duration = Fraction(audio.duration_pts, audio.time_base)
        if duration < 2 or duration > 15:
            _fail("audio_duration_invalid")
        total += duration
    if total > 15:
        _fail("audio_duration_invalid")
    if len({audio.sha256 for audio in audios}) != len(audios):
        _fail("audio_duplicate")
    return audios


def _validate_semantic_plan(
    *,
    visual: FrozenVisualInput,
    audios: tuple[FrozenReferenceAudio, ...],
    dialogue: object,
    subjects: object,
    sound_design: object,
) -> tuple[tuple[DialogueLine, ...], tuple[SubjectBinding, ...], SoundDesign]:
    lines = _require_tuple(dialogue, "dialogue_not_frozen")
    bindings = _require_tuple(subjects, "subjects_not_frozen")
    if not all(isinstance(line, DialogueLine) for line in lines):
        _fail("dialogue_invalid")
    if not all(isinstance(subject, SubjectBinding) for subject in bindings):
        _fail("subjects_invalid")
    if not isinstance(sound_design, SoundDesign):
        _fail("sound_design_invalid")

    if tuple(sorted(line.order for line in lines)) != tuple(
        line.order for line in lines
    ):
        _fail("dialogue_order_invalid")
    narration = sound_design.narration
    if tuple(sorted(line.order for line in narration)) != tuple(
        line.order for line in narration
    ):
        _fail("narration_order_invalid")
    speaking_orders = sorted(
        [line.order for line in lines] + [line.order for line in narration]
    )
    if speaking_orders != list(range(1, len(speaking_orders) + 1)):
        _fail("dialogue_order_invalid")

    subject_ids = [subject.subject_id for subject in bindings]
    expected_subject_ids = [f"S{index}" for index in range(1, len(bindings) + 1)]
    if subject_ids != expected_subject_ids:
        _fail("subject_order_invalid")
    if len(set(subject_ids)) != len(subject_ids):
        _fail("speaker_ambiguous")
    by_subject = {subject.subject_id: subject for subject in bindings}
    if any(line.subject_id not in by_subject for line in lines):
        _fail("speaker_unbound")
    speaking_subject_ids = {line.subject_id for line in lines}
    for subject in bindings:
        is_speaking = subject.subject_id in speaking_subject_ids
        if is_speaking != (subject.voice_ref is not None):
            _fail("speaker_unbound")

    picture_count = len(visual.keyframes)
    used_voice_refs: set[int] = set()
    for subject in bindings:
        if any(reference > picture_count for reference in subject.picture_refs):
            _fail("speaker_unbound")
        if subject.voice_ref is None:
            continue
        if subject.voice_ref > len(audios) or subject.voice_ref in used_voice_refs:
            _fail("speaker_ambiguous")
        if audios[subject.voice_ref - 1].kind != "voice":
            _fail("speaker_unbound")
        used_voice_refs.add(subject.voice_ref)

    narrator_voice_refs = {
        line.voice_ref for line in narration if line.voice_ref is not None
    }
    if narrator_voice_refs.intersection(used_voice_refs):
        _fail("speaker_ambiguous")
    for voice_ref in narrator_voice_refs:
        if voice_ref > len(audios) or audios[voice_ref - 1].kind != "voice":
            _fail("speaker_unbound")
    used_voice_refs.update(narrator_voice_refs)

    sound_refs = sound_design.ambience_refs + sound_design.effects
    sound_indexes = [reference.audio_index for reference in sound_refs]
    if len(sound_indexes) != len(set(sound_indexes)):
        _fail("sound_reference_duplicate")
    for reference in sound_design.ambience_refs:
        if reference.audio_index > len(audios) or audios[
            reference.audio_index - 1
        ].kind != "ambience":
            _fail("sound_reference_kind_mismatch")
    for reference in sound_design.effects:
        if reference.audio_index > len(audios) or audios[
            reference.audio_index - 1
        ].kind != "sound_effect":
            _fail("sound_reference_kind_mismatch")

    expected_sound_refs = {
        audio.order for audio in audios if audio.kind in {"ambience", "sound_effect"}
    }
    if set(sound_indexes) != expected_sound_refs:
        _fail("sound_reference_unbound")
    expected_voice_refs = {audio.order for audio in audios if audio.kind == "voice"}
    if used_voice_refs != expected_voice_refs:
        _fail("voice_reference_unbound")
    return lines, bindings, sound_design


def _picture_list(references: tuple[int, ...]) -> str:
    return ", ".join(f"<Picture {reference}>" for reference in references)


def compile_multimodal_prompt(
    *,
    visual: FrozenVisualInput,
    audio_references: tuple[FrozenReferenceAudio, ...],
    dialogue: tuple[DialogueLine, ...],
    subjects: tuple[SubjectBinding, ...],
    sound_design: SoundDesign,
) -> str:
    """Compile exact, ordered H3 Context-IR; never concatenate a free final prompt."""

    _validate_visual(visual)
    audios = _validate_audio_references(audio_references)
    lines, bindings, sound_design = _validate_semantic_plan(
        visual=visual,
        audios=audios,
        dialogue=dialogue,
        subjects=subjects,
        sound_design=sound_design,
    )
    if (
        _RESERVED_PROMPT_SYNTAX.search(visual.prompt)
        or "<" in visual.prompt
        or ">" in visual.prompt
    ):
        _fail("visual_prompt_reserved_syntax")

    definitions = [
        f"<Picture {frame.order}> is ordered reference image "
        f"{json.dumps(frame.name, ensure_ascii=False)} ({frame.width}x{frame.height}); "
        "use it only for visible appearance, composition, and continuity."
        for frame in visual.keyframes
    ]
    for subject in bindings:
        subject_number = int(subject.subject_id[1:])
        if subject.voice_ref is None:
            definitions.append(
                f"<Subject {subject_number}>({subject.subject_id}) is a silent visual subject "
                f"shown in {_picture_list(subject.picture_refs)}; do not make this subject speak."
            )
        else:
            definitions.append(
                f"<Subject {subject_number}>({subject.subject_id}) is the speaking subject shown "
                f"in {_picture_list(subject.picture_refs)}. <Audio {subject.voice_ref}> supplies "
                "voice timbre and delivery only for this subject; it is conditioning, not a "
                "target audio track."
            )
    for reference in sound_design.ambience_refs:
        definitions.append(
            f"<Audio {reference.audio_index}> is an ambience conditioning reference only: "
            f"{reference.description}."
        )
    for reference in sound_design.effects:
        definitions.append(
            f"<Audio {reference.audio_index}> is a sound-effect conditioning reference only: "
            f"{reference.description}."
        )
    for line in sound_design.narration:
        if line.voice_ref is not None:
            definitions.append(
                f"<Audio {line.voice_ref}> supplies voice timbre and delivery only for the "
                "off-screen narrator; it is conditioning, not a target audio track."
            )

    summary_refs = " ".join(
        [f"<Picture {frame.order}>" for frame in visual.keyframes]
        + [f"<Audio {audio.order}>" for audio in audios]
    )
    spoken: list[tuple[int, str]] = []
    for line in lines:
        subject_number = int(line.subject_id[1:])
        spoken.append(
            (
                line.order,
                f"[Speaking event {line.order}] <Subject {subject_number}>({line.subject_id}) "
                "says exactly: "
                f"<d>[{line.language}]{line.text}</d>",
            )
        )
    for line in sound_design.narration:
        voice_clause = (
            f" using <Audio {line.voice_ref}>" if line.voice_ref is not None else ""
        )
        spoken.append(
            (
                line.order,
                f"[Speaking event {line.order}] The off-screen narrator{voice_clause} says "
                f"exactly: <d>[{line.language}]{line.text}</d>; no visible subject lip-syncs it.",
            )
        )
    spoken.sort(key=lambda item: item[0])
    speaking_block = "\n".join(text for _, text in spoken) or (
        "No dialogue or narration. Do not invent speech, singing, or voice-over."
    )
    sound_intents = [
        reference.description
        for reference in sound_design.ambience_refs + sound_design.effects
    ]
    soundscape = "; ".join(sound_intents) if sound_intents else (
        "Only scene-synchronous sound implied by the frozen visual semantics; do not invent music."
    )

    prompt = (
        "subject_definitions:\n"
        + "\n".join(definitions)
        + "\n\nsummary:\n"
        + f"[reference generation + native audio] Use the ordered references {summary_refs}; "
        + "generate picture and sound jointly, preserving every explicit binding below.\n\n"
        + "source_visual_semantics:\n"
        + visual.prompt
        + "\nOnly visible semantics from this source section apply; ignore any speech or "
        + "sound instruction that may appear in legacy prose."
        + "\n\nretention_analysis:\n"
        + "Picture references control visible semantics only. Audio references provide "
        + "conditioning semantics only and must not be copied or treated as a complete "
        + "target track.\n\n"
        + "detailed_description:\n"
        + speaking_block
        + "\n\noverall_soundscape:\n"
        + soundscape
        + "\n\nnon_diegetic_music:\nN/A\n"
    )
    if len(prompt.encode("utf-8")) > MAX_PROMPT_BYTES:
        _fail("effective_prompt_too_large")
    return prompt


def consume_skill_prompt_plan(
    prompt_plan: object,
    *,
    visual: FrozenVisualInput,
    audio_references: Sequence[FrozenReferenceAudio],
) -> H3SemanticInput:
    """Strictly consume the optional video-maker VA semantic projection.

    Skill JSON owns only 1-based semantic references.  Frozen media bytes,
    hashes, probe evidence, mode, quote, and request identity remain owned by
    this backend contract.
    """

    plan = _skill_object(
        prompt_plan,
        frozenset(
            {
                "version",
                "phase",
                "eligible",
                "reason",
                "visual_prompt",
                "subjects",
                "audio_refs",
                "dialogue",
                "sound_design",
            }
        ),
    )
    if plan["version"] != 1 or plan["phase"] != "multimodal_audio":
        _fail("skill_plan_shape_invalid")
    if not isinstance(plan["eligible"], bool):
        _fail("skill_plan_shape_invalid")
    if plan["eligible"] is not True:
        _require_nonblank(plan["reason"], "skill_plan_shape_invalid")
        failed_sound_design = _skill_object(
            plan["sound_design"],
            frozenset({"narration", "ambience_refs", "effects"}),
        )
        if (
            plan["visual_prompt"] != ""
            or plan["subjects"] != []
            or plan["audio_refs"] != []
            or plan["dialogue"] != []
            or any(value != [] for value in failed_sound_design.values())
        ):
            _fail("skill_plan_shape_invalid")
        _fail("skill_plan_ineligible")
    if plan["reason"] is not None or plan["visual_prompt"] != visual.prompt:
        _fail("skill_plan_visual_mismatch")

    visual = _validate_visual(visual)
    audios = _validate_audio_references(tuple(audio_references))

    subjects = _skill_items(
        plan["subjects"],
        frozenset({"subject_id", "picture_refs", "voice_ref"}),
        lambda item: SubjectBinding(
            item["subject_id"],
            tuple(_skill_list(item["picture_refs"])),
            item["voice_ref"],
        ),
    )
    dialogue = _skill_items(
        plan["dialogue"],
        frozenset({"order", "subject_id", "language", "text"}),
        lambda item: DialogueLine(
            item["order"], item["subject_id"], item["language"], item["text"]
        ),
    )

    raw_sound_design = _skill_object(
        plan["sound_design"],
        frozenset({"narration", "ambience_refs", "effects"}),
    )
    narration = _skill_items(
        raw_sound_design["narration"],
        frozenset({"order", "language", "text", "voice_ref"}),
        lambda item: NarrationLine(
            item["order"], item["voice_ref"], item["language"], item["text"]
        ),
    )
    sound_keys = frozenset({"audio_index", "description"})

    def consume_sounds(value: object) -> tuple:
        return _skill_items(
            value,
            sound_keys,
            lambda item: SoundReference(item["audio_index"], item["description"]),
        )

    sound_design = SoundDesign(
        narration=narration,
        ambience_refs=consume_sounds(raw_sound_design["ambience_refs"]),
        effects=consume_sounds(raw_sound_design["effects"]),
    )
    lines, bindings, sound_design = _validate_semantic_plan(
        visual=visual,
        audios=audios,
        dialogue=dialogue,
        subjects=subjects,
        sound_design=sound_design,
    )

    expected_audio_bindings: dict[int, tuple[str, str | None]] = {}
    for subject in bindings:
        if subject.voice_ref is not None:
            expected_audio_bindings[subject.voice_ref] = ("voice", subject.subject_id)
    for line in sound_design.narration:
        if line.voice_ref is not None:
            expected_audio_bindings[line.voice_ref] = ("voice", None)
    for reference in sound_design.ambience_refs:
        expected_audio_bindings[reference.audio_index] = ("ambience", None)
    for reference in sound_design.effects:
        expected_audio_bindings[reference.audio_index] = ("sound_effect", None)

    raw_audio_refs = _skill_list(plan["audio_refs"])
    if len(raw_audio_refs) != len(audios):
        _fail("skill_audio_refs_mismatch")
    for expected_index, raw_audio_ref in enumerate(raw_audio_refs, 1):
        audio_ref = _skill_object(
            raw_audio_ref,
            frozenset({"audio_index", "purpose", "subject_id"}),
        )
        if audio_ref["purpose"] not in {"voice", "ambience", "effect"}:
            _fail("skill_audio_refs_mismatch")
        normalized_purpose = (
            "sound_effect"
            if audio_ref["purpose"] == "effect"
            else audio_ref["purpose"]
        )
        binding = (normalized_purpose, audio_ref["subject_id"])
        if (
            audio_ref["audio_index"] != expected_index
            or audios[expected_index - 1].kind != normalized_purpose
            or expected_audio_bindings.get(expected_index) != binding
        ):
            _fail("skill_audio_refs_mismatch")

    return H3SemanticInput(
        audio_references=audios,
        dialogue=lines,
        subjects=bindings,
        sound_design=sound_design,
    )


def preview_multimodal_plan(
    *,
    visual: FrozenVisualInput,
    audio_references: Sequence[FrozenReferenceAudio],
    dialogue: Sequence[DialogueLine],
    subjects: Sequence[SubjectBinding],
    sound_design: SoundDesign,
    mode: H3Mode,
    duration: int,
    resolution: str,
    aspect_ratio: str,
    plan_id: str,
    revision: int,
) -> H3MultimodalPlan:
    """Validate and project one quote/plan/compiled-prompt truth for approval."""

    visual = _validate_visual(visual)
    audios = _validate_audio_references(tuple(audio_references))
    dialogue_tuple, subject_tuple, sound_design = _validate_semantic_plan(
        visual=visual,
        audios=audios,
        dialogue=tuple(dialogue),
        subjects=tuple(subjects),
        sound_design=sound_design,
    )
    workflow, quote = _execution_spec(
        mode=mode,
        resolution=resolution,
        aspect_ratio=aspect_ratio,
        duration=duration,
    )
    _require_nonblank(plan_id, "invalid_plan_id")
    _require_positive_integer(revision, "invalid_revision")
    effective_prompt = compile_multimodal_prompt(
        visual=visual,
        audio_references=audios,
        dialogue=dialogue_tuple,
        subjects=subject_tuple,
        sound_design=sound_design,
    )
    return H3MultimodalPlan(
        visual=visual,
        audio_references=audios,
        dialogue=dialogue_tuple,
        subjects=subject_tuple,
        sound_design=sound_design,
        mode=mode,
        duration=duration,
        resolution=resolution,
        aspect_ratio=aspect_ratio,
        workflow=workflow,
        quote=quote,
        plan_id=plan_id,
        revision=revision,
        effective_prompt=effective_prompt,
        effective_prompt_sha256=_sha256(effective_prompt.encode("utf-8")),
    )


def _validate_plan(plan: object) -> H3MultimodalPlan:
    if not isinstance(plan, H3MultimodalPlan):
        _fail("plan_invalid")
    if (
        plan.compiler_version != COMPILER_VERSION
        or plan.audio_required is not True
        or plan.reference_audio_semantics != REFERENCE_AUDIO_SEMANTICS
        or plan.output_audio_authority != OUTPUT_AUDIO_AUTHORITY
    ):
        _fail("plan_contract_mismatch")
    visual = _validate_visual(plan.visual)
    audios = _validate_audio_references(plan.audio_references)
    lines, subjects, sound_design = _validate_semantic_plan(
        visual=visual,
        audios=audios,
        dialogue=plan.dialogue,
        subjects=plan.subjects,
        sound_design=plan.sound_design,
    )
    workflow, quote = _execution_spec(
        mode=plan.mode,
        resolution=plan.resolution,
        aspect_ratio=plan.aspect_ratio,
        duration=plan.duration,
    )
    if workflow != plan.workflow or quote != plan.quote:
        _fail("plan_execution_mismatch")
    _require_nonblank(plan.plan_id, "invalid_plan_id")
    _require_positive_integer(plan.revision, "invalid_revision")
    effective_prompt = compile_multimodal_prompt(
        visual=visual,
        audio_references=audios,
        dialogue=lines,
        subjects=subjects,
        sound_design=sound_design,
    )
    if (
        effective_prompt != plan.effective_prompt
        or _sha256(effective_prompt.encode("utf-8"))
        != plan.effective_prompt_sha256
    ):
        _fail("prompt_script_mismatch")
    if _canonical_sha256(_plan_manifest(plan)) != plan.plan_sha256:
        _fail("plan_hash_mismatch")
    return plan


def freeze_multimodal_request(
    *,
    plan: H3MultimodalPlan,
    approved_plan_sha256: str,
    approved_by: str,
    idempotency_key: str,
) -> H3MultimodalRequest:
    """Bind an explicit approval and idempotency key to one exact plan revision."""

    plan = _validate_plan(plan)
    if not _is_sha256(approved_plan_sha256) or (
        approved_plan_sha256 != plan.plan_sha256
    ):
        _fail("approval_mismatch")
    _require_nonblank(approved_by, "approval_invalid")
    _require_nonblank(idempotency_key, "invalid_idempotency")
    return H3MultimodalRequest(
        plan=plan,
        approved_plan_sha256=approved_plan_sha256,
        approved_by=approved_by,
        idempotency_key=idempotency_key,
    )


def _validate_request(request: object) -> H3MultimodalRequest:
    if not isinstance(request, H3MultimodalRequest):
        _fail("request_invalid")
    plan = _validate_plan(request.plan)
    if request.approved_plan_sha256 != plan.plan_sha256:
        _fail("approval_mismatch")
    _require_nonblank(request.approved_by, "approval_invalid")
    _require_nonblank(request.idempotency_key, "invalid_idempotency")
    if _canonical_sha256(_request_manifest(request)) != request.request_sha256:
        _fail("request_hash_mismatch")
    return request


def _data_uri(data: bytes, mime_type: str) -> str:
    return f"data:{mime_type};base64," + base64.b64encode(data).decode("ascii")


def build_autodl_request(request: H3MultimodalRequest) -> BuiltAutodlRequest:
    """Build the exact AutoDL request body from frozen bytes; never performs I/O."""

    request = _validate_request(request)
    plan = request.plan
    body: dict[str, object] = {
        "prompt": plan.effective_prompt,
        "duration": plan.duration,
        "resolution": plan.resolution + (
            "横" if plan.aspect_ratio == "16:9" else "竖"
        ),
        "audio_required": True,
    }
    for frame in plan.visual.keyframes:
        mime_type = _IMAGE_MIME_BY_SUFFIX[Path(frame.name).suffix.lower()]
        body[f"ref_image_{frame.order - 1}"] = _data_uri(frame.data, mime_type)
    for audio in plan.audio_references:
        body[f"ref_audio_{audio.order - 1}"] = _data_uri(
            audio.data, _AUDIO_MIME_BY_FORMAT[audio.format]
        )
    return BuiltAutodlRequest(
        workflow=plan.workflow,
        body=body,
        idempotency_key=request.idempotency_key,
        request_sha256=request.request_sha256,
        plan_sha256=plan.plan_sha256,
        payload_sha256=_canonical_sha256(body),
    )
