import 'antd/dist/reset.css';

export {
  Alert,
  App as AntApp,
  AutoComplete,
  Avatar,
  Badge,
  Button,
  Card,
  Checkbox,
  Collapse,
  Col,
  Descriptions,
  Divider,
  Drawer,
  Dropdown,
  Empty,
  Flex,
  Form,
  Grid,
  Image,
  Input,
  Layout,
  List,
  Menu,
  Modal,
  Popconfirm,
  Progress,
  Radio,
  Result,
  Row,
  Segmented,
  Select,
  Skeleton,
  Space,
  Spin,
  Steps,
  Statistic,
  Switch,
  Tabs,
  Tag,
  Timeline,
  Tooltip,
  Typography,
  Upload,
} from 'antd';
export type {
  FormInstance,
  ThemeConfig,
  UploadFile,
  UploadProps,
} from 'antd';

export {
  Actions,
  Attachments,
  Bubble,
  Conversations,
  FileCard,
  Prompts,
  Sender,
  Sources,
  Suggestion,
  ThoughtChain,
  Welcome,
  XProvider,
} from '@ant-design/x';
export { default as zhCN } from '@ant-design/x/locale/zh_CN';

export {
  CheckCircleFilled,
  ClockCircleOutlined,
  CloseOutlined,
  CopyOutlined,
  DeleteOutlined,
  DownloadOutlined,
  EditOutlined,
  ExclamationCircleOutlined,
  FileImageOutlined,
  FileOutlined,
  LinkOutlined,
  LockOutlined,
  LogoutOutlined,
  MenuOutlined,
  MoreOutlined,
  PlusOutlined,
  ProductOutlined,
  ReloadOutlined,
  ScissorOutlined,
  SendOutlined,
  SettingOutlined,
  TranslationOutlined,
  UploadOutlined,
  UserOutlined,
  VideoCameraAddOutlined,
  VideoCameraOutlined,
} from '@ant-design/icons';

export { Video } from './video';
export type { VideoProps } from './video';
